### PR TITLE
Adjustments to multi-model setup

### PR DESCRIPTION
**Pull request by clairefro**
Thank you so much for kick starting the model override feature. 

I made a few updates before being able to merge your branch:
- Changed order of settings to group settings logically
- Added spacing between settings sections to keep things clearer
- Added explicit error handling for when a model is not found
- Updated "Asking ChatCBT..." modal to include the current mode and model for transparency 
- Updated README to include mention of model override features

Relates to https://github.com/clairefro/obsidian-chat-cbt-plugin/issues/2

image

image

### CODE REVIEW

**Comment by clairefro** [comment]
(PS, I will add an editor config file as a separate PR to the main repo after I merge your changes :) )

**Comment by clairefro** [comment]
Fixed loading modal message to properly display the mode and model, regardless of whether using defaults or override 

image
image

**Comment by IbragimovDP** [comment]
@clairefro Hello!
Sorry for long response and thank you for your changes🫶

**Comment by clairefro** [comment]
Thank you! Changes officially available in 1.0.3 release 

Simply [update your Obsidian plugins](https://help.obsidian.md/Extending+Obsidian/Community+plugins#:~:text=Update%20plugins&text=To%20update%20all%20your%20plugins,are%20available%2C%20select%20Update%20all.) to access

**Pull request merged**
